### ISSUE TITLE
Python 2.6: OrderedDict fallback needed

### ISSUE THREAD

**Issue by jayvdb** [Sean1708/reFILE#2]
``` python
Traceback (most recent call last):
  File ".tox/py26/bin/refile", line 7, in <module>
    from refile.cmdline import main
  File "/home/travis/build/jayvdb/urllib3/.tox/py26/lib/python2.6/site-packages/refile/cmdline.py", line 3, in <module>
    from . import engine
  File "/home/travis/build/jayvdb/urllib3/.tox/py26/lib/python2.6/site-packages/refile/engine.py", line 7, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict
```

https://travis-ci.org/jayvdb/urllib3/jobs/86768683

**Comment by jayvdb** [comment]
Python 2.6 `unittest` does not include assertSetEqual, so `nose.tools.assert_set_equal` is also missing.
(and `assert_dict_contains_subset` and `assert_not_in`)
